<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.0+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [5]:
# Get scalar back as Python integer
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [9]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([3, 5])

In [14]:
MATRIX[0][1]

tensor(5)

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR.ndim

3

In [19]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [20]:
TENSOR[0, 0, 1]

tensor(5)