<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.1+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get scalar back as Python integer
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [ ]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([3, 5])

In [ ]:
MATRIX[0][1]

tensor(5)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [ ]:
TENSOR[0, 0, 1]

tensor(5)

### **Random Tensors**
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2686, 0.2211, 0.2179, 0.4259],
        [0.6587, 0.3579, 0.9630, 0.8708],
        [0.2236, 0.2842, 0.1843, 0.7785]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[1.9315e-01, 3.1622e-01, 8.2328e-01],
         [2.0079e-01, 9.4070e-01, 6.1208e-01],
         [7.2495e-01, 4.8949e-01, 7.7849e-01],
         ...,
         [8.8711e-01, 3.1441e-01, 9.6790e-02],
         [7.5533e-01, 7.8980e-01, 5.4834e-01],
         [6.9891e-01, 2.8685e-01, 6.7010e-01]],

        [[4.9099e-01, 6.8209e-01, 3.1118e-01],
         [1.8172e-01, 6.8697e-01, 7.2316e-01],
         [7.8581e-01, 6.1417e-01, 2.4106e-01],
         ...,
         [3.4701e-01, 7.7765e-01, 5.9066e-01],
         [3.2272e-01, 9.1979e-01, 4.9587e-01],
         [6.6465e-01, 2.2112e-01, 1.8623e-02]],

        [[8.7463e-01, 3.3448e-01, 8.5517e-01],
         [7.1534e-01, 7.7637e-01, 9.6578e-01],
         [5.9824e-01, 4.1239e-01, 3.0232e-01],
         ...,
         [5.0744e-01, 7.1152e-01, 2.0844e-01],
         [7.2406e-01, 5.6371e-01, 9.3669e-01],
         [6.2391e-01, 4.3929e-01, 6.6264e-01]],

        ...,

        [[2.7447e-01, 3.5979e-01, 5.8970e-02],
         [3.4918e-01, 9.3502e-02, 7.2232e-01]

### Zeros and ones

In [ ]:
# Create a tensor of all zeors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a trernsor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange() instead of torch.range()
zero_to_thousand = torch.arange(start=0, end=1000, step=68)
zero_to_thousand

tensor([  0,  68, 136, 204, 272, 340, 408, 476, 544, 612, 680, 748, 816, 884,
        952])

In [ ]:
# Creating tensors like
zeroes_like = torch.zeros_like(input=zero_to_thousand)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
3-possible tensor errors

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 8.0],
                               dtype=None)
print(float_32_tensor.dtype) # Default tensor datatype is float 32

float_16_tensor = torch.tensor([5.0, 6.0, 4.3],
                               dtype=torch.float16, # What datatype is the tensor (e.g. float32 -> single precision more digits, float16 -> half precision faster operations, complex32, )
                               device=None, # What device is your tensor on, You cannot do an operation between two tensors that are on the different devices
                               requires_grad=False) # Pytorch to track the gradient
float_16_tensor.dtype

torch.float32


torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 8.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 64.])

In [ ]:
int_32_tensor = torch.tensor([3, 7, 8],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 42., 64.])

### Getting Information From Tensors (tensor attributes)




To get datatype: tensor.dtype

To get shpe from tensor: tensor.hape

To get device from tensor: tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4673, 0.9764, 0.5950, 0.9214],
        [0.3960, 0.5494, 0.9474, 0.4666],
        [0.4358, 0.4210, 0.6824, 0.5124]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4673, 0.9764, 0.5950, 0.9214],
        [0.3960, 0.5494, 0.9474, 0.4666],
        [0.4358, 0.4210, 0.6824, 0.5124]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


  ### Tensor Operations

  Tensor operations include:
  - Addition
  - Subtractinn
  - Multiplication (element-wise)
  - Division
  - Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 4, 6])
# Addition
tensor = tensor + 10
tensor

tensor([11, 14, 16])

In [ ]:
# Multiplication
tensor = tensor * 10
tensor

tensor([110, 140, 160])

In [ ]:
# Subtraction
tensor = tensor - 10
tensor

tensor([100, 130, 150])

In [ ]:
# Try out pytorch in built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([110, 140, 160])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learnning:

1) Element-wise multiplication

2) Matrix multiplication (dot product)

In [ ]:
 # Element wise multiplication
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([100, 130, 150]) * tensor([100, 130, 150])
Equals: tensor([10000, 16900, 22500])


In [ ]:
# Matrix Multiplication
torch.matmul( tensor, tensor)

tensor(49400)

It is a lot faster to do it by using pytorch matmul method than doing it by hand

### One of the most common errors in deep learning: Shape errors
##There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match: (@ means matrix multiplication)
* (3, **2**) @ (**3**, 2) wont work
* (2, **3**) @ (**3**, 2) will work
* (3, **2**) @ (**2**, 3) will work
2. The resulting matrix has the shape of **outer dimensions**
* (2, 3) @ (3, 2)  ---> (2, 2)
* (3, 2) @ (2, 3)  ---> (2, 2)

# Shapes for maatrix multiplication

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmmul
# It wont work

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])


tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix our tensor shape issues, we can manipulatae the shape of one of our tensors using transpose.

 A **transpose** switches the axes or the dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplicationn operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange( 0, 100, 10).type(dtype = torch.float16) # Default dtype is long then it gives error in the mean method
x, x.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16),
 torch.float16)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0., dtype=torch.float16), tensor(0., dtype=torch.float16))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90., dtype=torch.float16), tensor(90., dtype=torch.float16))

In [ ]:
# Find the mean (requires a tensor of float datatype to work)
torch.mean(x)

tensor(45., dtype=torch.float16)

In [ ]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450., dtype=torch.float16), tensor(450., dtype=torch.float16))

## Finding the positional min and max

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Find the position in tensorr that has the minimum value with argmin() -> returns index of minimum argument
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# Find position of the max
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueeezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeeze - removes all '1' dimensions from a tensor

* Unsqueeze - add a '1' dimension to a target tensor

* Permute - Return a vieew of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9) # Like the same shape with reshape
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # vstack and hstack is changing the dim here
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all sin gle dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [ ]:
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previoous targeet: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew shape: {x_unsqueezed.shape}")
print(f"New tensor: {x_unsqueezed}")

Previoous targeet: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New shape: torch.Size([1, 9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width] // If we cahange a value at original one, permuted version will be changed too.

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing with NumPy


In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1] #same as x[0, 1]

tensor([4, 5, 6])

In [ ]:
# Let's index on the most inner brackket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# You can also use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact wwith it.

* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'

* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'


In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # .type(torch.float32), when converting numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor # tensor does not change

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to numpy_tensor ?
tensor = tensor + 1
tensor, numpy_tensor # it does not change, there is no reference connection between them

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbbers to try and make them better representations of the data -> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentually what the random seed does is "flavour" the randomness.

In [8]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3759, 0.9748, 0.5959, 0.5400],
        [0.7491, 0.1057, 0.1602, 0.5142],
        [0.5074, 0.2975, 0.9837, 0.9069]])
tensor([[0.7719, 0.8260, 0.8188, 0.7235],
        [0.7011, 0.2281, 0.3556, 0.2562],
        [0.0550, 0.6463, 0.7113, 0.4189]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [13]:
# Let's make some random but reproducible tensors

import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # for it to use the same seed, you shoould set the random seed every time before a block
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors annd PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVİDİA hardware + PyTorch working behinf the scenes to make everything good

from sre_constants import GROUPREF_UNI_IGNORE
### 1. Getting a GPU

1. Easiest - Use Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure,these services allow you to rent computers on the cloud and access them

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.


In [1]:
!nvidia-smi

Sat Jul 20 19:37:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

###2. Check for GPU access with PyTorch

In [2]:
# Check for the GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of runninng compute on the GPU or Pu, it is best practice to setup device agnostic code.

In [4]:
# Setup deice agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/ models on the GPU is because using a GPU results in faster computations.


In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor is not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [11]:
# If tensor is on GPU, can't transfor it to NumPy
# tensor_on_gpu.numpy() -> gives error  can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')