<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.0+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [6]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]

tensor([3, 5])

In [11]:
MATRIX[0][1]

tensor(5)

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [16]:
TENSOR[0, 0, 1]

tensor(5)

### **Random Tensors**
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0392, 0.0075, 0.5124, 0.2215],
        [0.5951, 0.7739, 0.0868, 0.4484],
        [0.2095, 0.1653, 0.3527, 0.9565]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_image_size_tensor

tensor([[[0.1680, 0.1144, 0.3000],
         [0.2540, 0.9247, 0.2725],
         [0.4136, 0.0528, 0.1134],
         ...,
         [0.1495, 0.2679, 0.7396],
         [0.5528, 0.2433, 0.1090],
         [0.4934, 0.8835, 0.8573]],

        [[0.9788, 0.9582, 0.1237],
         [0.2407, 0.7265, 0.9639],
         [0.1534, 0.5244, 0.5196],
         ...,
         [0.6024, 0.1598, 0.4180],
         [0.7725, 0.1535, 0.5541],
         [0.5209, 0.5362, 0.3963]],

        [[0.2348, 0.1348, 0.5602],
         [0.0474, 0.0804, 0.9671],
         [0.7009, 0.7046, 0.6421],
         ...,
         [0.4817, 0.1037, 0.0940],
         [0.0326, 0.6472, 0.4856],
         [0.7397, 0.1488, 0.0724]],

        ...,

        [[0.2737, 0.1839, 0.0785],
         [0.2525, 0.3188, 0.8103],
         [0.3375, 0.1523, 0.1984],
         ...,
         [0.9138, 0.7332, 0.4915],
         [0.8689, 0.3002, 0.5195],
         [0.8420, 0.1653, 0.9496]],

        [[0.4539, 0.2525, 0.1531],
         [0.5942, 0.7613, 0.3900],
         [0.

### Zeros and ones

In [21]:
# Create a tensor of all zeors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a trernsor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [26]:
# Use torch.arange() instead of torch.range()
zero_to_thousand = torch.arange(start=0, end=1000, step=68)
zero_to_thousand

tensor([  0,  68, 136, 204, 272, 340, 408, 476, 544, 612, 680, 748, 816, 884,
        952])

In [27]:
# Creating tensors like
zeroes_like = torch.zeros_like(input=zero_to_thousand)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
3-possible tensor errors

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 8.0],
                               dtype=None)
print(float_32_tensor.dtype) # Default tensor datatype is float 32

float_16_tensor = torch.tensor([5.0, 6.0, 4.3],
                               dtype=torch.float16, # What datatype is the tensor (e.g. float32 -> single precision more digits, float16 -> half precision faster operations, complex32, )
                               device="cuda", # What device is your tensor on, You cannot do an operation between two tensors that are on the different devices
                               requires_grad=False) # Pytorch to track the gradient
float_16_tensor.dtype

torch.float32


torch.float16

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 8.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 64.])