<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.0+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get scalar back as Python integer
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [ ]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([3, 5])

In [ ]:
MATRIX[0][1]

tensor(5)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [ ]:
TENSOR[0, 0, 1]

tensor(5)

### **Random Tensors**
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [4]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2, 4, 4)
random_tensor

tensor([[[0.1989, 0.0382, 0.6465, 0.9932],
         [0.6618, 0.4855, 0.8560, 0.7786],
         [0.8580, 0.1359, 0.0821, 0.6684],
         [0.5732, 0.2946, 0.5125, 0.4137]],

        [[0.6770, 0.3551, 0.2947, 0.3339],
         [0.6317, 0.7958, 0.5944, 0.4213],
         [0.1798, 0.3120, 0.9134, 0.2444],
         [0.3674, 0.6853, 0.6099, 0.4407]]])

In [5]:
random_tensor.ndim

3

In [6]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor