<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.1+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [6]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]

tensor([3, 5])

In [11]:
MATRIX[0][1]

tensor(5)

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [16]:
TENSOR[0, 0, 1]

tensor(5)

### **Random Tensors**
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7571, 0.4206, 0.1488, 0.7296],
        [0.7036, 0.0739, 0.0232, 0.7375],
        [0.7420, 0.7423, 0.8405, 0.7597]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_image_size_tensor

tensor([[[0.0312, 0.9668, 0.1565],
         [0.4697, 0.6165, 0.6982],
         [0.0633, 0.8754, 0.6356],
         ...,
         [0.7614, 0.7478, 0.4553],
         [0.0308, 0.8512, 0.3409],
         [0.7420, 0.9731, 0.0521]],

        [[0.6784, 0.6801, 0.8449],
         [0.4391, 0.0372, 0.9194],
         [0.7626, 0.3994, 0.2184],
         ...,
         [0.6398, 0.5302, 0.4930],
         [0.8979, 0.0565, 0.5612],
         [0.1412, 0.1555, 0.4713]],

        [[0.0565, 0.3398, 0.7405],
         [0.8810, 0.5968, 0.8386],
         [0.4103, 0.9120, 0.3075],
         ...,
         [0.1980, 0.6047, 0.2218],
         [0.2044, 0.5622, 0.2467],
         [0.4466, 0.0261, 0.9370]],

        ...,

        [[0.6396, 0.7049, 0.3152],
         [0.8489, 0.5667, 0.7451],
         [0.0549, 0.6395, 0.9110],
         ...,
         [0.5670, 0.1411, 0.0053],
         [0.1502, 0.3238, 0.7652],
         [0.2863, 0.7048, 0.1472]],

        [[0.5519, 0.8950, 0.1005],
         [0.9800, 0.4552, 0.2214],
         [0.

### Zeros and ones

In [21]:
# Create a tensor of all zeors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a trernsor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [26]:
# Use torch.arange() instead of torch.range()
zero_to_thousand = torch.arange(start=0, end=1000, step=68)
zero_to_thousand

tensor([  0,  68, 136, 204, 272, 340, 408, 476, 544, 612, 680, 748, 816, 884,
        952])

In [27]:
# Creating tensors like
zeroes_like = torch.zeros_like(input=zero_to_thousand)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
3-possible tensor errors

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 8.0],
                               dtype=None)
print(float_32_tensor.dtype) # Default tensor datatype is float 32

float_16_tensor = torch.tensor([5.0, 6.0, 4.3],
                               dtype=torch.float16, # What datatype is the tensor (e.g. float32 -> single precision more digits, float16 -> half precision faster operations, complex32, )
                               device=None, # What device is your tensor on, You cannot do an operation between two tensors that are on the different devices
                               requires_grad=False) # Pytorch to track the gradient
float_16_tensor.dtype

torch.float32


torch.float16

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 8.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 64.])

In [31]:
int_32_tensor = torch.tensor([3, 7, 8],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 42., 64.])

### Getting Information From Tensors (tensor attributes)




To get datatype: tensor.dtype

To get shpe from tensor: tensor.hape

To get device from tensor: tensor.device

In [33]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0245, 0.2844, 0.8621, 0.6671],
        [0.8455, 0.1140, 0.3178, 0.0993],
        [0.1393, 0.3930, 0.1957, 0.6589]])

In [34]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0245, 0.2844, 0.8621, 0.6671],
        [0.8455, 0.1140, 0.3178, 0.0993],
        [0.1393, 0.3930, 0.1957, 0.6589]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


  ### Tensor Operations

  Tensor operations include:
  - Addition
  - Subtractinn
  - Multiplication (element-wise)
  - Division
  - Matrix multiplication

In [35]:
# Create a tensor
tensor = torch.tensor([1, 4, 6])
# Addition
tensor = tensor + 10
tensor

tensor([11, 14, 16])

In [36]:
# Multiplication
tensor = tensor * 10
tensor

tensor([110, 140, 160])

In [37]:
# Subtraction
tensor = tensor - 10
tensor

tensor([100, 130, 150])

In [38]:
# Try out pytorch in built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([110, 140, 160])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learnning:

1) Element-wise multiplication

2) Matrix multiplication (dot product)

In [39]:
 # Element wise multiplication
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([100, 130, 150]) * tensor([100, 130, 150])
Equals: tensor([10000, 16900, 22500])


In [40]:
# Matrix Multiplication
torch.matmul( tensor, tensor)

tensor(49400)

It is a lot faster to do it by using pytorch matmul method than doing it by hand

### One of the most common errors in deep learning: Shape errors
##There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match: (@ means matrix multiplication)
* (3, **2**) @ (**3**, 2) wont work
* (2, **3**) @ (**3**, 2) will work
* (3, **2**) @ (**2**, 3) will work
2. The resulting matrix has the shape of **outer dimensions**
* (2, 3) @ (3, 2)  ---> (2, 2)
* (3, 2) @ (2, 3)  ---> (2, 2)

# Shapes for maatrix multiplication

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmmul
# It wont work

In [45]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])


tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix our tensor shape issues, we can manipulatae the shape of one of our tensors using transpose.

 A **transpose** switches the axes or the dimensions of a given tensor.

In [47]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [48]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [49]:
# The matrix multiplicationn operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [50]:
x = torch.arange( 0, 100, 10).type(dtype = torch.float16) # Default dtype is long then it gives error in the mean method
x, x.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16),
 torch.float16)

In [51]:
# Find the min
torch.min(x), x.min()

(tensor(0., dtype=torch.float16), tensor(0., dtype=torch.float16))

In [52]:
# Find the max
torch.max(x), x.max()

(tensor(90., dtype=torch.float16), tensor(90., dtype=torch.float16))

In [53]:
# Find the mean (requires a tensor of float datatype to work)
torch.mean(x)

tensor(45., dtype=torch.float16)

In [54]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450., dtype=torch.float16), tensor(450., dtype=torch.float16))

## Finding the positional min and max

In [55]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [56]:
# Find the position in tensorr that has the minimum value with argmin() -> returns index of minimum argument
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [57]:
# Find position of the max
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueeezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeeze - removes all '1' dimensions from a tensor

* Unsqueeze - add a '1' dimension to a target tensor

* Permute - Return a vieew of the input with dimensions permuted (swapped) in a certain way.

In [58]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Change the view
z = x.view(1, 9) # Like the same shape with reshape
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # vstack and hstack is changing the dim here
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [68]:
# torch.squeeze() - removes all sin gle dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [70]:
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [74]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previoous targeet: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew shape: {x_unsqueezed.shape}")
print(f"New tensor: {x_unsqueezed}")

Previoous targeet: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New shape: torch.Size([1, 9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [76]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
