<a href="https://colab.research.google.com/github/MuhammedEmirEren/pytorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.0+cu121


# Tensors
Creating Tensors

pytorch tensors are created using torcch.tensor()
-->>> https://pytorch.org/docs/stable/tensors.html#initializing-and-basic-operations

.ndim is to get number of dimensions of tensor

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get scalar back as Python integer
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim
# Number of dimensions are acctually number of embedded square brackets
# like two dimensional arrays in java


1

In [6]:
vector.shape
# .shape is giving the dimensions in the coordinate system

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[3, 5],
                       [8, 7]])
MATRIX

tensor([[3, 5],
        [8, 7]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]

tensor([3, 5])

In [11]:
MATRIX[0][1]

tensor(5)

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 5, 8],
                        [4, 9, 7],
                        [5, 0, -1]]])
TENSOR

tensor([[[ 1,  5,  8],
         [ 4,  9,  7],
         [ 5,  0, -1]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
 TENSOR[0]

tensor([[ 1,  5,  8],
        [ 4,  9,  7],
        [ 5,  0, -1]])

In [16]:
TENSOR[0, 0, 1]

tensor(5)

### **Random Tensors**
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6308, 0.7285, 0.8207, 0.4760],
        [0.6849, 0.7437, 0.4520, 0.8927],
        [0.2605, 0.8994, 0.9036, 0.9344]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
random_image_size_tensor

tensor([[[0.3991, 0.4022, 0.5919],
         [0.0996, 0.5273, 0.0462],
         [0.4732, 0.4931, 0.3119],
         ...,
         [0.2744, 0.6988, 0.8897],
         [0.8076, 0.2274, 0.5004],
         [0.8848, 0.8656, 0.3798]],

        [[0.5171, 0.7564, 0.3443],
         [0.8622, 0.6179, 0.9630],
         [0.3884, 0.1440, 0.9429],
         ...,
         [0.4389, 0.5475, 0.0020],
         [0.0578, 0.1948, 0.1487],
         [0.0472, 0.7699, 0.5866]],

        [[0.7332, 0.2600, 0.9615],
         [0.6866, 0.2407, 0.8365],
         [0.3037, 0.9739, 0.2496],
         ...,
         [0.6139, 0.3377, 0.3655],
         [0.4617, 0.7441, 0.1793],
         [0.8362, 0.4611, 0.6363]],

        ...,

        [[0.4275, 0.7557, 0.4176],
         [0.0567, 0.4460, 0.0580],
         [0.4123, 0.7133, 0.1693],
         ...,
         [0.9830, 0.9628, 0.0635],
         [0.5977, 0.0394, 0.1109],
         [0.8494, 0.6782, 0.0783]],

        [[0.2793, 0.6771, 0.4876],
         [0.5110, 0.2233, 0.0282],
         [0.

### Zeros and ones

In [21]:
# Create a tensor of all zeors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a trernsor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [26]:
# Use torch.arange() instead of torch.range()
zero_to_thousand = torch.arange(start=0, end=1000, step=68)
zero_to_thousand

tensor([  0,  68, 136, 204, 272, 340, 408, 476, 544, 612, 680, 748, 816, 884,
        952])

In [27]:
# Creating tensors like
zeroes_like = torch.zeros_like(input=zero_to_thousand)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
3-possible tensor errors

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 8.0],
                               dtype=None)
print(float_32_tensor.dtype) # Default tensor datatype is float 32

float_16_tensor = torch.tensor([5.0, 6.0, 4.3],
                               dtype=torch.float16, # What datatype is the tensor (e.g. float32 -> single precision more digits, float16 -> half precision faster operations, complex32, )
                               device=None, # What device is your tensor on, You cannot do an operation between two tensors that are on the different devices
                               requires_grad=False) # Pytorch to track the gradient
float_16_tensor.dtype

torch.float32


torch.float16

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 8.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 64.])

In [31]:
int_32_tensor = torch.tensor([3, 7, 8],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 42., 64.])

### Getting Information From Tensors (tensor attributes)




To get datatype: tensor.dtype

To get shpe from tensor: tensor.hape

To get device from tensor: tensor.device

In [33]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3030, 0.9318, 0.2492, 0.3179],
        [0.8549, 0.4914, 0.9994, 0.6488],
        [0.5497, 0.6225, 0.3377, 0.9832]])

In [34]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3030, 0.9318, 0.2492, 0.3179],
        [0.8549, 0.4914, 0.9994, 0.6488],
        [0.5497, 0.6225, 0.3377, 0.9832]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


  ### Tensor Operations

  Tensor operations include:
  - Addition
  - Subtractinn
  - Multiplication (element-wise)
  - Division
  - Matrix multiplication

In [35]:
# Create a tensor
tensor = torch.tensor([1, 4, 6])
# Addition
tensor = tensor + 10
tensor

tensor([11, 14, 16])

In [36]:
# Multiplication
tensor = tensor * 10
tensor

tensor([110, 140, 160])

In [37]:
# Subtraction
tensor = tensor - 10
tensor

tensor([100, 130, 150])

In [38]:
# Try out pytorch in built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([110, 140, 160])

### Matrix Multiplication

Two main ways of performing multiplication in neural network and deep learnning:

1) Element-wise multiplication

2) Matrix multiplication (dot product)

In [39]:
 # Element wise multiplication
 print(tensor, "*", tensor)
 print(f"Equals: {tensor * tensor}")

tensor([100, 130, 150]) * tensor([100, 130, 150])
Equals: tensor([10000, 16900, 22500])


In [40]:
# Matrix Multiplication
torch.matmul( tensor, tensor)

tensor(49400)

It is a lot faster to do it by using pytorch matmul method than doing it by hand

### One of the most common errors in deep learning: Shape errors
##There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match: (@ means matrix multiplication)
* (3, **2**) @ (**3**, 2) wont work
* (2, **3**) @ (**3**, 2) will work
* (3, **2**) @ (**2**, 3) will work
2. The resulting matrix has the shape of **outer dimensions**
* (2, 3) @ (3, 2)  ---> (2, 2)
* (3, 2) @ (2, 3)  ---> (2, 2)

In [47]:
# Shapes for maatrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmmul
# It wont work

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix our tensor shape issues, we can manipulatae the shape of one of our tensors using transpose.

 A **transpose** switches the axes or the dimensions of a given tensor.

In [45]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [46]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [51]:
# The matrix multiplicationn operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))